approach: dvts
name: dvts

# search hyper-parameters (common across methods)
n_samples: 16
temperature: 1.0
top_p: 1.0
max_tokens: 2048
agg_strategy: mean         # [last, min, mean]
decoding_strategy: simple  # [simple, cot]

# beam search parameters
step_length: null
step_token: "\n\n"
beam_width: 4
max_search_steps: 40
filter_duplicates: false
sort_completed: false 

generation_results_path: null
